swagger: '2.0'
info:
  description: API for Digital Certificate 2.0 - VCF - ONLY MOCK
  version: v1
  title: VCF MOCK API
host: gw-azwe-dev.skoda-api.com
basePath: /it/solution/uvd-vcf-api-mock/v1
schemes:
  - https 
paths:
  /getrecord:
    get:
      summary: Get data for Digital Certificate 2.0
      parameters:
        - in: query
          name: format
          required: false
          type: string
          description: 'The format to return the response in, i.e. json.'
          default: '123456'          
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              vin: 
                type: string
                example: TMBGD21Z052092086
              skodaID: 
                type: string
                example: 987654-789123456
              mileageHistory:
                type: string
                example: 1257
definitions:
  getRecord:
    type: object
    properties:
      vin: 
        type: string
        example: TMBGD21Z052092086
      skodaID: 
        type: string
        example: 987654-789123456
      mileageHistory:
        type: string
        example: 1257
