openapi: 3.0.0
info:
  description: API for Digital Certificate 2.0 - VCF - ONLY MOCK
  version: v4
  title: VCF MOCK API OPENAPI
paths:
  '/vehicles/{VIN}/measurements':
    get:
      summary: Get measurements data for VCF
      parameters:
        - name: VIN
          in: path
          required: true
          description: Parameter for VIN code of vehicle
          schema:
            type: string
        - name: id
          in: query
          description: Query parameter for id (odometer)
          schema:
            type: string
      description: VCF mock - measurements
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMeasurementsRecord'
  /health:
    get:
      summary: Get info status
      responses:
        '204':
          description: Success
servers:
  - url: 'https://gw-azwe-dev.skoda-api.com/it/solution/uvd-vcf-api-mock-next/v4'
components:
  schemas:
    GetMeasurementsRecord:
      type: object
      properties:
        id:
          type: string
          description: id response
          example: 123456789
        carCapturedTimestamp:
          type: string
          description: date-time carCapturedTimestamp
          example: '2017-07-21T17:32:28Z'
        properties:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: name
              value:
                type: string
                example: 100