swagger: '2.0'
info:
  description: API for Digital Certificate 2.0 - VCF - ONLY MOCK
  version: v4
  title: VCF MOCK API NEXT

host: gw-azwe-dev.skoda-api.com
basePath: /it/solution/uvd-vcf-api-mock-next/v4
schemes:
  - https 
paths:
  /vehicles/{VIN}/measurements:
    get:
      summary: Get mock data for VCF
      parameters:
        - name: VIN
          in: path
          required: true
          description: Parameter for VIN code of vehicle
          type: string
        - name: id
          in: query
          type: string
          description: Query parameter for id (odometer)                
      description: VCF mock - measurements
      produces:
        - application/json
      responses:
        200:
          description: Success          
          schema:
            $ref: '#/definitions/GetMeasurementsRecord'          
  /health:
    get:
      summary: Get info status
      responses:
        204:
          description: Success

definitions:
  GetMeasurementsRecord:
    type: object
    properties:
      id: 
        type: string
        description: id response
        example: 123456789        
      carCapturedTimestamp: 
        type: string
        description: date-time carCapturedTimestamp
        example: '2017-07-21T17:32:28Z'
      'properties':
        type: array
        items:
          type: object
          properties:
            name:
              type: string
              example: name
            value:
              type: string
              example: 100
                            

